# Generated by Django 5.1.2 on 2024-10-14 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coutype', models.CharField(max_length=50, verbose_name='講座')),
                ('coumask', models.CharField(default='000', max_length=10, verbose_name='資格')),
                ('mon', models.IntegerField(default=3, verbose_name='月曜')),
                ('tue', models.IntegerField(default=3, verbose_name='火曜')),
                ('wed', models.IntegerField(default=3, verbose_name='水曜')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.CharField(default='000', max_length=10, verbose_name='完了')),
                ('applicated', models.CharField(default='000', max_length=10, verbose_name='申込')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
